#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
----------------------------------------------------------------------
List of SOAP error codes as documented in the Control Center Knowledge
Base; to be imported into SOAP scripts for error handling
----------------------------------------------------------------------

Copyright (c) 2023 Cisco and/or its affiliates.

This software is licensed to you under the terms of the Cisco Sample
Code License, Version 1.1 (the "License"). You may obtain a copy of the
License at

               https://developer.cisco.com/docs/licenses

All use of the material herein must be in accordance with the terms of
the License. All rights not expressly granted by the License are
reserved. Unless required by applicable law or agreed to separately in
writing, software distributed under the License is distributed on an "AS
IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
or implied.

"""

def SoapError(errno):
    errors = {
        "10000": "Wildcard search is too general",
        "10001": "Maximum size exceeded",
        "100000": "Device error",
        "100100": "Device not found. The ICCID doesn't exist in the caller's account. This type of error can occur when you try to use a sandbox account to access a production device.",
        "100101": "Invalid ICCID",
        "100200": "Invalid device change type",
        "100300": "Invalid edit terminal request",
        "100400": "Invalid device(s) specified",
        "100401": "Invalid device ID specified",
        "100500": "Offer not found",
        "100501": "Invalid offer",
        "100510": "Campaign not found",
        "100520": "Invalid rate plan",
        "200000": "Billing error",
        "200100": "Invoice does not exist",
        "200200": "No device usage found",
        "300000": "Admin error",
        "300100": "Invalid Qcode",
        "300200": "Invalid account name",
        "300201": "Account name not unique",
        "300300": "Invalid email",
        "300301": "Email not unique",
        "400000": "API error",
        "400100": "Invalid license key. Please use a valid API license key. Make sure you're using the correct license key for the current environment. Sometimes people mistakenly use their sandbox license key on the production site or vice versa.",
        "400101": "License has exceeded the rate limit for API calls.",
        "400200": "Security validation error. Your username or password is incorrect. Make sure you're using the right credentials for the current environment. Sometimes people mistakenly use their apitest credentials on the production site or vice versa.",
        "400201": "Access violation error. Please check your login; you may be trying to access a device that belongs to a different account or service provider. This error can happen if the caller has accounts with multiple service providers and they're using the login from the wrong service provider.",
        "400300": "System internal error",
        "400400": "Too many entries",
        "400500": "Invalid ICCID",
        "500000": "SMS error",
        "500100": "From Date greater than To Date",
        "500200": "Too many entries",
        "500300": "SMS message not found",
        "500400": "Message text null",
        "500500": "Message text greater than 160 characters",
        "500600": "Send message failure",
        "500700": "Device not active",
        "500800": "Decoding error",
        "500900": "Decoded message text null",
        "800000": "Network Access Config not found",
        "800100": "Invalid edit Network Access Config request",
        "900100": "No active session",
        "900101": "Protocol not supported",
        "900102": "Invalid port",
        "900103": "Communication failed",
        "900104": "Communication timeout",
        "1000100": "Account not found",
        "1000400": "Too many accounts",
        "1000500": "Service provider not found",
        "1000501": "Could not create account",
        "1000502": "Internal Error - default trial communication plan not found for service provider",
        "1000503": "Internal Error - default trial rate plan not found for service provider",
        "1000504": "Account already exists",
        "1000505": "Invalid region ID",
        "1000506": "Default communication plan not found for service provider",
        "1000507": "Service Provider Account ID is not unique; multiple accounts found.",
        "1000508": "Cannot transfer device to this account",
        "1000509": "Cannot transfer device to the same account",
        "1000510": "Cannot transfer device when one of the accounts is an inventory account",
        "1100100": "Edit device rating error",
        "1100200": "Term end date must be greater than term start date",
        "1100300": "Renewal rate plan is blank",
        "1100400": "Renewal rate plan is not valid for the device",
        "1100500": "Renewal mode is not valid",
        "1100600": "Access denied. Cannot edit term start and end dates",
        "1100700": "Failed to remove rate plan from queue",
        "1110100": "Add device renewal error",
        "1120100": "Edit LinePayStatus error",
        "1120101": "Invalid LinePayStatus parameter",
        "1120102": "Invalid operation for SimStatus is Purged",
        "1120104": "No terminals associated with Service Provider Account ID",
        "1200100": "Invalid event name",
        "1200200": "Event instance not found",
        "1200300": "Event instance started already",
        "1300100": "Configuration file not found",
        "1300200": "Failed to upload diagnostics data",
        "1300300": "Invalid sequence number",
        "1400100": "Try a different user name.",
        "1400101": "Customer not found",
        "1400102": "Role not found",
        "1400103": "Could not create user",
        "1400104": "Invalid password or invalid IP address",
        "1400105": "Invalid authentication token",
        "1400106": "Not authorized to create this role",
        "1400107": "Peered user information must be specified",
        "1400108": "Account not peered",
        "1400109": "User not found",
        "1400110": "Could not delete user",
        "1400111": "Could not reset user password",
        "1400133": "Password should not contain user name",
        "1400134": "Password contains consecutively repeated alphanumeric characters that exceeds the maximum",
        "1400135": "Password contains alphanumeric sequence that exceeds the maximum",
        "1401001": "Illegal characters in password",
        "1401002": "Password length less than the required minimum",
        "1401003": "Password length more than the maximum",
        "1401004": "Contains fewer alphabetic characters than the required minimum",
        "1401005": "Contains more alphabetic characters than the maximum",
        "1401006": "Contains fewer numeric characters than the required minimum",
        "1401007": "Contains more numeric characters than the maximum",
        "1401008": "Contains fewer special characters than the required minimum",
        "1401009": "Contains more special characters than the maximum",
        "1401010": "Password matches one of the previous passwords",
        "1401011": "Contains fewer uppercase characters than the required minimum",
        "1500100": "IMSI not found",
        "1500200": "Start Date is not before End Date",
        "1600100": "Invalid rate plan or not a wholesale rate plan",
        "1700100": "Invalid communication plan",
        "1700101": "Invalid APN",
        "1700102": "Invalid IP address",
        "1800100": "Unknown",
        "1800101": "Global SIM not found",
        "1800102": "Global partner not found",
        "1800103": "Invalid GlobalSimTransferId in the request",
        "1800104": "Invalid transfer request. Primary ICCID hasn't been transferred to any partner.",
        "1800105": "ICCID already has a global transfer pending.",
        "1800106": "ICCID doesn't have any pending Global Transfer request.",
        "1800107": "Global Alliance not found.",
        "1800108": "Target service provider doesn't exist.",
        "1800109": "Target Global SIM subscription information not found.",
        "1800110": "Account mapping not defined for Global SIM transfer.",
        "1800111": "Global SIM is in invalid state for Global SIM transfer.",
        "1800112": "Target subscription is already in use.",
        "1800113": "G&D IMSI swap failed for the Global SIM.",
        "1800114": "Cisco IMSI swap failed for the Global SIM.",
        "1800115": "Global SIM not live",
        "1800116": "Global SIM transfer can't be cancelled for the SIM at this stage.",
        "1800117": "Global SIM target subscription partially in use.",
        "1800118": "Global SIM target IMSI already in use.",
        "1800119": "Target SIM not present in expected account.",
        "1800120": "Subscription already associated with a chip.",
        "1800121": "No free slots found for chip.",
        "1800122": "Selected slot is not found for chip.",
        "1800123": "Selected slot is occupied for chip.",
        "1800124": "The provided login session is not valid.",
        "1800125": "The login session has expired, please re-authenticate.",
        "1800126": "The user is not authorized to perform the operation.",
        "1800127": "The user could not be found.",
        "1800128": "The provided password is not valid.",
        "1800129": "The user is blocked.",
        "1800130": "The user is expired.",
        "1800131": "Too many failed login attempts, user is now blocked.",
        "1800132": "Invalid request, duplicate messageId used.",
        "1800133": "Global SIM has always roaming reimsi rule associated with it.",
        "1800134": "Target Global SIM subscription mapping cannot be created.",
        "1800135": "Global SIM transfer type not specified.",
        "1800136": "Global SIM has already been transferred.",
        "1800138": "No suitable target subscription found in the inventory pool of the target account.",
        "1800139": "SIM Profile with given External Profile ID does not exist.",
        "1800140": "Target SIM does not exist.",
        "1800141": "Source SIM cannot be prepared for Global SIM transfer.",
        "1800142": "Source SIM cannot be un-prepared on failed Global SIM transfer.",
        "1800143": "Global SIM Profile mapping does not exist.",
        "1800144": "Target Global SIM subscription mapping does not exist.",
        "1800145": "The SIM is not of a valid Global SIM type.",
        "1800146": "Target SIM cannot be prepared for reverse Global SIM transfer.",
        "1800147": "Target SIM cannot be un-prepared on failed reverse Global SIM transfer.",
        "1800148": "Read timeout while invoking transfer scheduling API.",
        "1800149": "Connection timeout while invoking transfer scheduling API.",
        "1800150": "Error while invoking transfer scheduling API.",
        "1800160": "Error in changing SIM State.",
        "1800161": "Target SIM cannot be created for Global SIM transfer.",
        "1800162": "Source SIM cannot be deactivated for Global SIM transfer.",
        "1800163": "Target SIM cannot be activated for Global SIM transfer.",
        "1800164": "Global SIM is in invalid state for reverse Global SIM transfer.",
        "1800165": "Target SIM creation cannot be un-done on failed Global SIM transfer.",
        "1800166": "Global SIM transfer can't be resumed because it has already been scheduled for cancel.",
        "1800167": "Invalid cancel request. ICCID has no FAILED transfer associated with it.",
        "1800168": "G&D subscription cleanup failed for the Global SIM.",
        "1800169": "Internal configuration error in setting up the API invocation, please contact customer support.",
        "1800170": "The OTA Algorithm chosen for this partner is not supported. Please choose a different partner that supports G&D OTA algorithm.",
        "1800171": "Global SIM Transfer to Agency partners is not supported for now.",
        "1800172": "Global SIM target MSISDN assignment failed.",
        "1800173": "Can not get the acctBillSetting according to the ICCID.",
        "1800174": "Partner MSISDN Assignment API invocation limit reached.",
        "1800175": "Partner MSISDN Assignment API invocation failed.",
        "1800176": "G&D API authentication error: failed to verify password.",
        "1800177": "Could not update MSISDN on the Subscription, either IMSI is wrong or Subscription is locked due to Subscription Management activity.",
        "1800178": "Target Subscription is already associated with this chip.",
        "1800179": "Card Profile for the chip is not allowed by profile whitelist associated with the subscription.",
        "1800180": "Could not reserve the virtual subscription for a slot of the chip.",
        "1800181": "There is already an ongoing transaction for the chip.",
        "1800182": "Unhandled exception in G&D server.",
        "1800183": "Either IMSI or CustomerId is wrong, or IMSI is not associated with a Chip",
        "1800184": "Not possible to perform the operation on the subscription due to its wrong state.",
        "1800185": "Target virtual-subscription does not exist in G&D.",
        "1800186": "The target virtual-subscription either does not exist in G&D or cannot be imported from partner server.",
        "1800187": "The primary subscription does not exist in G&D.",
        "1800188": "The Account Custom Field or Service Provider account ID should not be null while making SolicitarSWAP request.",
        "1800189": "The request to the Target service provider's NMS for MSISDN assignment was not successful, and the swap has Failed.",
        "1800190": "The eUICC ID for the SIM is not found.",
        "1800191": "The request to the Target service provider's NMS for MSISDN assignment timed out, and the swap has Failed.",
        "1800195": "The G&D API invocation failed.",
        "1800601": "The SIM has a fixed IP Address.",
        "1800211": "The SIM is in an invalid state for InterSP Transfer.",
        "1800215": "There is no inventory account associate with the target SIM service provider."
    }

    return errors.get(errno, "Unknown Error")
